"""Model variables changed for Customer class

Revision ID: 4b70dad74bed
Revises: 
Create Date: 2025-02-28 13:06:37.221858

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b70dad74bed'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('first_name', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('last_name', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('customer_contact', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('customer_email', sa.String(length=50), nullable=False))
        batch_op.drop_constraint('customer_customer_reservation_key', type_='unique')
        batch_op.create_unique_constraint(None, ['customer_email'])
        batch_op.create_unique_constraint(None, ['customer_contact'])
        batch_op.drop_constraint('customer_reservation_id_fkey', type_='foreignkey')
        batch_op.drop_column('reservation_id')
        batch_op.drop_column('customer_name')
        batch_op.drop_column('customer_reservation')

    with op.batch_alter_table('reservation', schema=None) as batch_op:
        batch_op.alter_column('reservation_name',
               existing_type=sa.VARCHAR(length=75),
               type_=sa.String(length=50),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reservation', schema=None) as batch_op:
        batch_op.alter_column('reservation_name',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=75),
               existing_nullable=False)

    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('customer_reservation', sa.VARCHAR(length=75), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('customer_name', sa.TEXT(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('reservation_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('customer_reservation_id_fkey', 'reservation', ['reservation_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_unique_constraint('customer_customer_reservation_key', ['customer_reservation'])
        batch_op.drop_column('customer_email')
        batch_op.drop_column('customer_contact')
        batch_op.drop_column('last_name')
        batch_op.drop_column('first_name')

    # ### end Alembic commands ###
