"""Add customer_id to reservations

Revision ID: 51a3a34f78ce
Revises: 01b8b672b38a
Create Date: 2025-02-28 14:31:00.631145

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51a3a34f78ce'
down_revision = '01b8b672b38a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.alter_column('last_name',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=False)
        batch_op.drop_constraint('customer_customer_contact_key', type_='unique')
        batch_op.drop_constraint('customer_customer_email_key', type_='unique')
        batch_op.drop_constraint('customer_reservation_date_key', type_='unique')

    with op.batch_alter_table('reservation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('customer_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint('reservation_reservation_name_key', type_='unique')
        batch_op.create_foreign_key(None, 'customer', ['customer_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reservation', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_unique_constraint('reservation_reservation_name_key', ['reservation_name'])
        batch_op.drop_column('customer_id')

    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.create_unique_constraint('customer_reservation_date_key', ['reservation_date'])
        batch_op.create_unique_constraint('customer_customer_email_key', ['customer_email'])
        batch_op.create_unique_constraint('customer_customer_contact_key', ['customer_contact'])
        batch_op.alter_column('last_name',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=False)

    # ### end Alembic commands ###
